// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtgssyuqzdcpolxfvrdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10Z3NzeXVxemRjcG9seGZ2cmRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDM5MTAsImV4cCI6MjA3MDQxOTkxMH0.kHCzo6Jv1L8dRsAMltbGMdf_qgOfItvbDsK9P2M7fYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});